# YML code for blog
site_name: Ben McLeod
site_url: https://blog.ben-mcleod.com/
site_dir: public_html/blog/site
docs_dir: public_html/blog/docs
theme:
  name: material
  features:
    - navigation.sections
    # Adds Previous and Next arrows to the footer - navigation.footer
plugins:
  - blog:
      blog_dir: . 
  - search
  - tags
nav:
  - index.md
extra:
# Disable the standard footer
  generator: false
# Add social links to the footer
  social:
   - icon: fontawesome/brands/github 
     link: https://github.com/BenEmm
   - icon: fontawesome/brands/linkedin 
     link: https://www.linkedin.com/in/ben-mcleod/
copyright: Copyright &copy; 2024 Ben McLeod
  